#print("Programación" , "Fundamentos" , "en" )
#print("Python")

#LAB fomrateo de salida
print("idea principal:")
#######################
print("    /\ ")
print("   /  \ ")
print("  /    \ ")
print(" /      \ ")
print("/_      _\ ")
print()
print("  |    | ")
print("  |____| ")
#############################
print("con menos invocaciones de la función 'print()'")
print("    *\n   * *\n  *   *\n *     *\n***   ***")
print("  *   *\n  *   *\n  *****") 
#############################
print("Más alta:")
print("      /\ ")
print("     /  \ ")
print("    /    \ ")
print("   /      \ ")
print("  /        \ ")
print(" /          \ ")
print("/___      ___\ ")
print()
print("    |     |")
print("    |     | ")
print("    |_____| ")
###############################
print("Doubled:") 
print("      /\       "*2) 
print("     /  \      "*2) 
print("    /    \     "*2)
print("   /      \    "*2)
print("  /        \   "*2)
print(" /          \  "*2)
print("/___      ___\ "*2)
print()
print("    |     |    "*2)
print("    |     |    "*2)
print("    |_____|    "*2)